# Generated by Django 2.2.7 on 2020-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('overview', models.TextField(max_length=50)),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
